_target_: src.models.FunctionalSGD
lr: inv_n_samples
projector_y:
  _target_: sklearn.neighbors.KNeighborsRegressor
  weights: distance
  n_neighbors: 5
density_estimator_x:
  _target_: sklearn.neighbors.KernelDensity
  bandwidth: 1
  kernel: gaussian
density_estimator_z:
  _target_: sklearn.neighbors.KernelDensity
  bandwidth: 1
  kernel: gaussian
density_estimator_xz:
  _target_: sklearn.neighbors.KernelDensity
  bandwidth: 1
  kernel: gaussian
